//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppraisalSystem.Web.AccountService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccountService.IAccountWcfService")]
    public interface IAccountWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountWcfService/ValidateUser", ReplyAction="http://tempuri.org/IAccountWcfService/ValidateUserResponse")]
        bool ValidateUser(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountWcfService/ValidateUser", ReplyAction="http://tempuri.org/IAccountWcfService/ValidateUserResponse")]
        System.Threading.Tasks.Task<bool> ValidateUserAsync(string email, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccountWcfServiceChannel : AppraisalSystem.Web.AccountService.IAccountWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountWcfServiceClient : System.ServiceModel.ClientBase<AppraisalSystem.Web.AccountService.IAccountWcfService>, AppraisalSystem.Web.AccountService.IAccountWcfService {
        
        public AccountWcfServiceClient() {
        }
        
        public AccountWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ValidateUser(string email, string password) {
            return base.Channel.ValidateUser(email, password);
        }
        
        public System.Threading.Tasks.Task<bool> ValidateUserAsync(string email, string password) {
            return base.Channel.ValidateUserAsync(email, password);
        }
    }
}
