//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppraisalSystem.Web.PositionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PositionService.IPositionWcfService")]
    public interface IPositionWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPositionWcfService/GetAll", ReplyAction="http://tempuri.org/IPositionWcfService/GetAllResponse")]
        string[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPositionWcfService/GetAll", ReplyAction="http://tempuri.org/IPositionWcfService/GetAllResponse")]
        System.Threading.Tasks.Task<string[]> GetAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPositionWcfServiceChannel : AppraisalSystem.Web.PositionService.IPositionWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PositionWcfServiceClient : System.ServiceModel.ClientBase<AppraisalSystem.Web.PositionService.IPositionWcfService>, AppraisalSystem.Web.PositionService.IPositionWcfService {
        
        public PositionWcfServiceClient() {
        }
        
        public PositionWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PositionWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PositionWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PositionWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<string[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
    }
}
