//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppraisalSystem.Web.CompetenceService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CompetenceService.ICompetenceWcfService")]
    public interface ICompetenceWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompetenceWcfService/AddCompetence", ReplyAction="http://tempuri.org/ICompetenceWcfService/AddCompetenceResponse")]
        void AddCompetence(int id, string competenceName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompetenceWcfService/AddCompetence", ReplyAction="http://tempuri.org/ICompetenceWcfService/AddCompetenceResponse")]
        System.Threading.Tasks.Task AddCompetenceAsync(int id, string competenceName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompetenceWcfService/GetAllCompetence", ReplyAction="http://tempuri.org/ICompetenceWcfService/GetAllCompetenceResponse")]
        string[] GetAllCompetence();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompetenceWcfService/GetAllCompetence", ReplyAction="http://tempuri.org/ICompetenceWcfService/GetAllCompetenceResponse")]
        System.Threading.Tasks.Task<string[]> GetAllCompetenceAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICompetenceWcfServiceChannel : AppraisalSystem.Web.CompetenceService.ICompetenceWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CompetenceWcfServiceClient : System.ServiceModel.ClientBase<AppraisalSystem.Web.CompetenceService.ICompetenceWcfService>, AppraisalSystem.Web.CompetenceService.ICompetenceWcfService {
        
        public CompetenceWcfServiceClient() {
        }
        
        public CompetenceWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CompetenceWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompetenceWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompetenceWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddCompetence(int id, string competenceName) {
            base.Channel.AddCompetence(id, competenceName);
        }
        
        public System.Threading.Tasks.Task AddCompetenceAsync(int id, string competenceName) {
            return base.Channel.AddCompetenceAsync(id, competenceName);
        }
        
        public string[] GetAllCompetence() {
            return base.Channel.GetAllCompetence();
        }
        
        public System.Threading.Tasks.Task<string[]> GetAllCompetenceAsync() {
            return base.Channel.GetAllCompetenceAsync();
        }
    }
}
